### ISSUE TITLE
Upgrade to Samza 0.10?

### ISSUE THREAD

**Issue by george24601** [theduderog/hello-samza-confluent#1]
I am looking into Samza + Confluent now, mostly for stream-joins. 

Do you have update for Samza 0.10 + Confluent 1.0.1/2.0.1? If not, I can do it.

**Comment by theduderog** [comment]
@george24601, I don't have it handy.  If you do it, that'd be great.  Please share it.

For joins, you might be interested in a few things:
- An [Avro serde](https://github.com/quantiply/rico/blob/master/avro/src/main/java/com/quantiply/samza/serde/AvroSerde.java) which uses Confluent Schema Registry
- An [Avro join class](https://github.com/quantiply/rico/blob/master/avro/src/main/java/com/quantiply/avro/Join.java).  Here's [how to use it](https://github.com/quantiply/rico/blob/master/avro/src/test/java/com/quantiply/avro/JoinTest.java#L59-L71).
- [Support for Avro projections in Confluent Platform](https://github.com/confluentinc/schema-registry/pull/274).  This is useful for extracting the join key separately from other fields.  It's commited to master but not included in Confluent 2.0.1 for some reason
- Here's an example of a join job using all of the above

```
    //For new lookup messages, save them in the local KV store
    private void processDeployMsg(IncomingMessageEnvelope envelope, MessageCollector collector, TaskCoordinator coordinator) throws Exception {
        //Note that we're decoding the same binary message with the same serde/decoder
        //into two different projection objects, one for the primary key fields, one for the values.
        SvcAttributeValue attrValue = (SvcAttributeValue) avroSerde.fromBytes((byte[]) envelope.getMessage(), SvcAttributeValue.getClassSchema());
        SvcCallEventKey key = (SvcCallEventKey) avroSerde.fromBytes((byte[]) envelope.getMessage(), SvcCallEventKey.getClassSchema());
        //save in local KV store
        deployAttrs.put(key, attrValue);
    }

    //For new events, extract the key, lookup the join data and merge it
    private void processCallMsg(IncomingMessageEnvelope envelope, MessageCollector collector, TaskCoordinator coordinator, EventStreamMetrics streamMetrics) throws Exception {
        //Get all the data (not a projection)
        SvcCallEvent call = (SvcCallEvent) avroSerde.fromBytes((byte []) envelope.getMessage());
        //Get the lookup key by projection
        SvcCallEventKey key = (SvcCallEventKey) avroSerde.fromBytes((byte []) envelope.getMessage(), SvcCallEventKey.getClassSchema());
        SvcAttributeValue attr = deployAttrs.get(key);

        GenericData.Record enriched = new Join(SvcCallEventWDeploy.getClassSchema())
                .merge(call)
                .merge(attr)
                .getBuilder()
                .set("header", getCamusHeaders(call.getHeader(), Headers.getClassSchema(), tsNowMs))
                .build();

        collector.send(new OutgoingMessageEnvelope(outSysStream, avroSerde.toBytes(enriched)));
    }
```

**Comment by george24601** [comment]
Thanks for the input. I tried it out and here are things to update
1. [Update Kafka producer config](https://github.com/theduderog/hello-samza-confluent/blob/master/src/main/config/seer.properties#L43)
2. [Similar to this example](https://github.com/quantiply/rico/blob/b4265231bec914982e7a6c8f6891eee4cdd3432e/core/src/main/java/com/quantiply/samza/task/AvroToJSONTask.java), add code to init avroSerde in SeerTask
3. As in your example, code to convert envelope.getMessage() to the Java type. Note that I had to cherry pick your projection change to build a custom serializer jar. If I use SpecificData.get().deepCopy() to convert, I ran into casting avro.Utf8 to String issue, because we have that utf8 to string setting in pom.xml

**Comment by george24601** [comment]
To make this work out of the box, we have a few options
1. Include the snapshot jar in lib
2. publish the snapshot jar in a maven repo
3. Take out the snapshot jar part, and use Utf8 in generated class instead of String 

I prefer option 3, because we can modify the code easily when the official serializer is released
