### ISSUE TITLE
Upgrade to Confluent 2.0.1

### ISSUE THREAD

**Issue by george24601** [theduderog/hello-samza-confluent#8]
As per [discussion](https://groups.google.com/forum/#!topic/confluent-platform/HMx0MUzkAKY), upgrading Confluent to 2.0.1 and Kafka to 0.9 solves the deserialization problem.

However, Samza 0.10 doesn't support Kafka 0.9 yet. 
(EDIT: here I meant Kafka 0.9's jar in dependency)

Note that the install script needs to be upgraded as well

**Comment by theduderog** [comment]
Done in another pull request.  I think Samza 0.10 works with Kafka 0.9 as long as you don't use compression on compacted topics without the patches.

**Comment by george24601** [comment]
In our environment, Samza 0.10 works fine with Kafka 0.9 brokers, just that I have to use 0.8.2.2's jar in dependency. See [this thread](https://mail-archives.apache.org/mod_mbox/samza-dev/201602.mbox/%3CCAFvExu0xoiMyyb+i=AK2TD0dwWi1zQ18QgupadUwNNgnRhvDGg@mail.gmail.com%3E).

**Comment by theduderog** [comment]
Got it. Thanks.
